### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by flybd5** [MicrosoftLearning/Docker-Build#2]
The readme file says how to create the package, but stops there and doesn't tell the reader how to actually use the thing. ???

**Comment by seesharprun** [comment]
After you complete step 4, you will have an output folder with two zip files. One contains the Allfiles zip file and the other containers the lab instructions in another zip file.

Should I add a step 5 that details this?

**Comment by flybd5** [comment]
I'm not sure I understand the value of this. The files you talk about are already on Github, here:

https://github.com/MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator

What's the point of jumping through these hoops to get the same thing? I thought this would add value by creating work environments to do the labs, etc. but it doesn't do anything like that. ??

**Comment by seesharprun** [comment]
That repo is closed in favor of [AZ-104](https://github.com/MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator).

This repo is unrelated to AZ-104. This repo is for course authors who want to use Docker to automate the build steps to convert the lab instructions into Word documents for distribution to students. I just took a look and AZ-104 doesn't participate in the build process or use this repo.

The lab environments for most RB-ILT is hosted by Authorized Lab Hosts (ALH).

**Comment by flybd5** [comment]
Except the AZ-103 test is still available. I took the test once and failed because the real test has no resemblance to the practice exams, and I just want to finish that and get my MCT fee while the fee is waived  until Sep 30. <sigh> One was to wonder if MS has any real interest in gaining new MCT's. All this hoop-jumping makes me want to just roundfile the whole idea and teach something else for a sane company.

**Comment by seesharprun** [comment]
These repositories are used for ILT classes. MCTs use them to prepare for classes and ALHs use them to keep their lab instructions up-to-date.

Lab environments are available for current MCTs using the MCT benefit page or for learning partners using the online store platform. I don't know of any other method to get a lab environment.

If you don't have a MCT credential, you can use Microsoft Learn to study for the AZ-104 certification exam: <https://docs.microsoft.com/en-us/learn/paths/az-104-administrator-prerequisites/>. Microsoft Learn will provision an Azure subscription for you to use while learning.

I'm a volunteer who manager this repository. I don't have any insight into what Microsoft is planning as far as strategy.

**Comment by flybd5** [comment]
I used MS Learn. That training has no relevance to the exam.

---------
A black hole marks the spot where your deity divided by zero.
